// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Exam.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package chat;

public interface ChatEngine extends Ice.Object,
                                    _ChatEngineOperations, _ChatEngineOperationsNC
{
    public static final String ice_staticId = "::chat::ChatEngine";

    public static final long serialVersionUID = 4571277025996773043L;
}
