// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `exam-2.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package distributedSynchronization;

public interface Arbiter extends Ice.Object,
                                 _ArbiterOperations, _ArbiterOperationsNC
{
    public static final String ice_staticId = "::distributedSynchronization::Arbiter";

    public static final long serialVersionUID = 4013538191005246247L;
}
