// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `exam-2.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package distributedSynchronization;

/**
 * Provides type-specific helper functions.
 **/
public final class ArbiterPrxHelper extends Ice.ObjectPrxHelperBase implements ArbiterPrx
{
    private static final String __give_name = "give";

    public void give()
    {
        give(null, false);
    }

    public void give(java.util.Map<String, String> __ctx)
    {
        give(__ctx, true);
    }

    private void give(java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_give(begin_give(__ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_give()
    {
        return begin_give(null, false, false, null);
    }

    public Ice.AsyncResult begin_give(java.util.Map<String, String> __ctx)
    {
        return begin_give(__ctx, true, false, null);
    }

    public Ice.AsyncResult begin_give(Ice.Callback __cb)
    {
        return begin_give(null, false, false, __cb);
    }

    public Ice.AsyncResult begin_give(java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_give(__ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_give(Callback_Arbiter_give __cb)
    {
        return begin_give(null, false, false, __cb);
    }

    public Ice.AsyncResult begin_give(java.util.Map<String, String> __ctx, Callback_Arbiter_give __cb)
    {
        return begin_give(__ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_give(IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_give(null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_give(IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_give(null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_give(java.util.Map<String, String> __ctx, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_give(__ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_give(java.util.Map<String, String> __ctx, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_give(__ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_give(java.util.Map<String, String> __ctx, 
                                       boolean __explicitCtx, 
                                       boolean __synchronous, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_give(__ctx, 
                          __explicitCtx, 
                          __synchronous, 
                          new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_give(java.util.Map<String, String> __ctx, 
                                       boolean __explicitCtx, 
                                       boolean __synchronous, 
                                       IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__give_name, __cb);
        try
        {
            __result.prepare(__give_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            __result.writeEmptyParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_give(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __give_name);
    }

    private static final String __take_name = "take";

    public boolean take()
    {
        return take(null, false);
    }

    public boolean take(java.util.Map<String, String> __ctx)
    {
        return take(__ctx, true);
    }

    private boolean take(java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__take_name);
        return end_take(begin_take(__ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_take()
    {
        return begin_take(null, false, false, null);
    }

    public Ice.AsyncResult begin_take(java.util.Map<String, String> __ctx)
    {
        return begin_take(__ctx, true, false, null);
    }

    public Ice.AsyncResult begin_take(Ice.Callback __cb)
    {
        return begin_take(null, false, false, __cb);
    }

    public Ice.AsyncResult begin_take(java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_take(__ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_take(Callback_Arbiter_take __cb)
    {
        return begin_take(null, false, false, __cb);
    }

    public Ice.AsyncResult begin_take(java.util.Map<String, String> __ctx, Callback_Arbiter_take __cb)
    {
        return begin_take(__ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_take(IceInternal.Functional_BoolCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_take(null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_take(IceInternal.Functional_BoolCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_take(null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_take(java.util.Map<String, String> __ctx, 
                                      IceInternal.Functional_BoolCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_take(__ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_take(java.util.Map<String, String> __ctx, 
                                      IceInternal.Functional_BoolCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_take(__ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_take(java.util.Map<String, String> __ctx, 
                                       boolean __explicitCtx, 
                                       boolean __synchronous, 
                                       IceInternal.Functional_BoolCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_take(__ctx, __explicitCtx, __synchronous, 
                          new IceInternal.Functional_TwowayCallbackBool(__responseCb, __exceptionCb, __sentCb)
                              {
                                  public final void __completed(Ice.AsyncResult __result)
                                  {
                                      ArbiterPrxHelper.__take_completed(this, __result);
                                  }
                              });
    }

    private Ice.AsyncResult begin_take(java.util.Map<String, String> __ctx, 
                                       boolean __explicitCtx, 
                                       boolean __synchronous, 
                                       IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__take_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__take_name, __cb);
        try
        {
            __result.prepare(__take_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            __result.writeEmptyParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public boolean end_take(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __take_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            boolean __ret;
            __ret = __is.readBool();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __take_completed(Ice.TwowayCallbackBool __cb, Ice.AsyncResult __result)
    {
        distributedSynchronization.ArbiterPrx __proxy = (distributedSynchronization.ArbiterPrx)__result.getProxy();
        boolean __ret = false;
        try
        {
            __ret = __proxy.end_take(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static ArbiterPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), ArbiterPrx.class, ArbiterPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static ArbiterPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), ArbiterPrx.class, ArbiterPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static ArbiterPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), ArbiterPrx.class, ArbiterPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static ArbiterPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), ArbiterPrx.class, ArbiterPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static ArbiterPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, ArbiterPrx.class, ArbiterPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static ArbiterPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, ArbiterPrx.class, ArbiterPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::distributedSynchronization::Arbiter"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, ArbiterPrx v)
    {
        __os.writeProxy(v);
    }

    public static ArbiterPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            ArbiterPrxHelper result = new ArbiterPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
