// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `exam-2.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package distributedSynchronization;

public final class ArbiterHolder extends Ice.ObjectHolderBase<Arbiter>
{
    public
    ArbiterHolder()
    {
    }

    public
    ArbiterHolder(Arbiter value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof Arbiter)
        {
            value = (Arbiter)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _ArbiterDisp.ice_staticId();
    }
}
