// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Exam.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package voting;

public interface _Callback_Voter_vote extends Ice.TwowayCallback
{
    public void response(int __ret, int[] votes);
}
