// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Exam.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package voting;

public final class VoterPrxHolder
{
    public
    VoterPrxHolder()
    {
    }

    public
    VoterPrxHolder(VoterPrx value)
    {
        this.value = value;
    }

    public VoterPrx value;
}
