// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Calculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package utils;

public final class CalculatorPrxHelper extends Ice.ObjectPrxHelperBase implements CalculatorPrx
{
    private static final String __gcd_name = "gcd";

    public long gcd(long x, long y)
    {
        return gcd(x, y, null, false);
    }

    public long gcd(long x, long y, java.util.Map<String, String> __ctx)
    {
        return gcd(x, y, __ctx, true);
    }

    private long gcd(long x, long y, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__gcd_name);
        return end_gcd(begin_gcd(x, y, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_gcd(long x, long y)
    {
        return begin_gcd(x, y, null, false, false, null);
    }

    public Ice.AsyncResult begin_gcd(long x, long y, java.util.Map<String, String> __ctx)
    {
        return begin_gcd(x, y, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_gcd(long x, long y, Ice.Callback __cb)
    {
        return begin_gcd(x, y, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_gcd(long x, long y, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_gcd(x, y, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_gcd(long x, long y, Callback_Calculator_gcd __cb)
    {
        return begin_gcd(x, y, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_gcd(long x, long y, java.util.Map<String, String> __ctx, Callback_Calculator_gcd __cb)
    {
        return begin_gcd(x, y, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_gcd(long x, 
                                     long y, 
                                     IceInternal.Functional_LongCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_gcd(x, y, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_gcd(long x, 
                                     long y, 
                                     IceInternal.Functional_LongCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                     IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_gcd(x, y, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_gcd(long x, 
                                     long y, 
                                     java.util.Map<String, String> __ctx, 
                                     IceInternal.Functional_LongCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_gcd(x, y, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_gcd(long x, 
                                     long y, 
                                     java.util.Map<String, String> __ctx, 
                                     IceInternal.Functional_LongCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                     IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_gcd(x, y, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_gcd(long x, 
                                      long y, 
                                      java.util.Map<String, String> __ctx, 
                                      boolean __explicitCtx, 
                                      boolean __synchronous, 
                                      IceInternal.Functional_LongCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_gcd(x, y, __ctx, __explicitCtx, __synchronous, 
                         new IceInternal.Functional_TwowayCallbackLong(__responseCb, __exceptionCb, __sentCb)
                             {
                                 public final void __completed(Ice.AsyncResult __result)
                                 {
                                     CalculatorPrxHelper.__gcd_completed(this, __result);
                                 }
                             });
    }

    private Ice.AsyncResult begin_gcd(long x, 
                                      long y, 
                                      java.util.Map<String, String> __ctx, 
                                      boolean __explicitCtx, 
                                      boolean __synchronous, 
                                      IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__gcd_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__gcd_name, __cb);
        try
        {
            __result.prepare(__gcd_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeLong(x);
            __os.writeLong(y);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public long end_gcd(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __gcd_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            long __ret;
            __ret = __is.readLong();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __gcd_completed(Ice.TwowayCallbackLong __cb, Ice.AsyncResult __result)
    {
        utils.CalculatorPrx __proxy = (utils.CalculatorPrx)__result.getProxy();
        long __ret = 0;
        try
        {
            __ret = __proxy.end_gcd(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    private static final String __lcm_name = "lcm";

    public long lcm(long x, long y)
    {
        return lcm(x, y, null, false);
    }

    public long lcm(long x, long y, java.util.Map<String, String> __ctx)
    {
        return lcm(x, y, __ctx, true);
    }

    private long lcm(long x, long y, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__lcm_name);
        return end_lcm(begin_lcm(x, y, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_lcm(long x, long y)
    {
        return begin_lcm(x, y, null, false, false, null);
    }

    public Ice.AsyncResult begin_lcm(long x, long y, java.util.Map<String, String> __ctx)
    {
        return begin_lcm(x, y, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_lcm(long x, long y, Ice.Callback __cb)
    {
        return begin_lcm(x, y, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_lcm(long x, long y, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_lcm(x, y, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_lcm(long x, long y, Callback_Calculator_lcm __cb)
    {
        return begin_lcm(x, y, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_lcm(long x, long y, java.util.Map<String, String> __ctx, Callback_Calculator_lcm __cb)
    {
        return begin_lcm(x, y, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_lcm(long x, 
                                     long y, 
                                     IceInternal.Functional_LongCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_lcm(x, y, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_lcm(long x, 
                                     long y, 
                                     IceInternal.Functional_LongCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                     IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_lcm(x, y, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_lcm(long x, 
                                     long y, 
                                     java.util.Map<String, String> __ctx, 
                                     IceInternal.Functional_LongCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_lcm(x, y, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_lcm(long x, 
                                     long y, 
                                     java.util.Map<String, String> __ctx, 
                                     IceInternal.Functional_LongCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                     IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_lcm(x, y, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_lcm(long x, 
                                      long y, 
                                      java.util.Map<String, String> __ctx, 
                                      boolean __explicitCtx, 
                                      boolean __synchronous, 
                                      IceInternal.Functional_LongCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_lcm(x, y, __ctx, __explicitCtx, __synchronous, 
                         new IceInternal.Functional_TwowayCallbackLong(__responseCb, __exceptionCb, __sentCb)
                             {
                                 public final void __completed(Ice.AsyncResult __result)
                                 {
                                     CalculatorPrxHelper.__lcm_completed(this, __result);
                                 }
                             });
    }

    private Ice.AsyncResult begin_lcm(long x, 
                                      long y, 
                                      java.util.Map<String, String> __ctx, 
                                      boolean __explicitCtx, 
                                      boolean __synchronous, 
                                      IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__lcm_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__lcm_name, __cb);
        try
        {
            __result.prepare(__lcm_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeLong(x);
            __os.writeLong(y);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public long end_lcm(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __lcm_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            long __ret;
            __ret = __is.readLong();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __lcm_completed(Ice.TwowayCallbackLong __cb, Ice.AsyncResult __result)
    {
        utils.CalculatorPrx __proxy = (utils.CalculatorPrx)__result.getProxy();
        long __ret = 0;
        try
        {
            __ret = __proxy.end_lcm(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    public static CalculatorPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), CalculatorPrx.class, CalculatorPrxHelper.class);
    }

    public static CalculatorPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), CalculatorPrx.class, CalculatorPrxHelper.class);
    }

    public static CalculatorPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), CalculatorPrx.class, CalculatorPrxHelper.class);
    }

    public static CalculatorPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), CalculatorPrx.class, CalculatorPrxHelper.class);
    }

    public static CalculatorPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, CalculatorPrx.class, CalculatorPrxHelper.class);
    }

    public static CalculatorPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, CalculatorPrx.class, CalculatorPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::utils::Calculator"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, CalculatorPrx v)
    {
        __os.writeProxy(v);
    }

    public static CalculatorPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            CalculatorPrxHelper result = new CalculatorPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
