// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Calculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package utils;

public interface CalculatorPrx extends Ice.ObjectPrx
{
    public long gcd(long x, long y);

    public long gcd(long x, long y, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_gcd(long x, long y);

    public Ice.AsyncResult begin_gcd(long x, long y, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_gcd(long x, long y, Ice.Callback __cb);

    public Ice.AsyncResult begin_gcd(long x, long y, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_gcd(long x, long y, Callback_Calculator_gcd __cb);

    public Ice.AsyncResult begin_gcd(long x, long y, java.util.Map<String, String> __ctx, Callback_Calculator_gcd __cb);

    public Ice.AsyncResult begin_gcd(long x, 
                                     long y, 
                                     IceInternal.Functional_LongCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_gcd(long x, 
                                     long y, 
                                     IceInternal.Functional_LongCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                     IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_gcd(long x, 
                                     long y, 
                                     java.util.Map<String, String> __ctx, 
                                     IceInternal.Functional_LongCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_gcd(long x, 
                                     long y, 
                                     java.util.Map<String, String> __ctx, 
                                     IceInternal.Functional_LongCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                     IceInternal.Functional_BoolCallback __sentCb);

    public long end_gcd(Ice.AsyncResult __result);

    public long lcm(long x, long y);

    public long lcm(long x, long y, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_lcm(long x, long y);

    public Ice.AsyncResult begin_lcm(long x, long y, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_lcm(long x, long y, Ice.Callback __cb);

    public Ice.AsyncResult begin_lcm(long x, long y, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_lcm(long x, long y, Callback_Calculator_lcm __cb);

    public Ice.AsyncResult begin_lcm(long x, long y, java.util.Map<String, String> __ctx, Callback_Calculator_lcm __cb);

    public Ice.AsyncResult begin_lcm(long x, 
                                     long y, 
                                     IceInternal.Functional_LongCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_lcm(long x, 
                                     long y, 
                                     IceInternal.Functional_LongCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                     IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_lcm(long x, 
                                     long y, 
                                     java.util.Map<String, String> __ctx, 
                                     IceInternal.Functional_LongCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_lcm(long x, 
                                     long y, 
                                     java.util.Map<String, String> __ctx, 
                                     IceInternal.Functional_LongCallback __responseCb, 
                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                     IceInternal.Functional_BoolCallback __sentCb);

    public long end_lcm(Ice.AsyncResult __result);
}
