// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ice_storm_chat_utils;

public interface ChatManager extends Ice.Object,
                                     _ChatManagerOperations, _ChatManagerOperationsNC
{
    public static final String ice_staticId = "::chatIceStorm::ChatManager";

    public static final long serialVersionUID = 3037443556326224694L;
}
