// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `WalkieTalkie.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package walkietalkie;

public interface WTPrx extends Ice.ObjectPrx
{
    public void pushMessage(String message);

    public void pushMessage(String message, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_pushMessage(String message);

    public Ice.AsyncResult begin_pushMessage(String message, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_pushMessage(String message, Ice.Callback __cb);

    public Ice.AsyncResult begin_pushMessage(String message, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_pushMessage(String message, Callback_WT_pushMessage __cb);

    public Ice.AsyncResult begin_pushMessage(String message, java.util.Map<String, String> __ctx, Callback_WT_pushMessage __cb);

    public Ice.AsyncResult begin_pushMessage(String message, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_pushMessage(String message, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_pushMessage(String message, 
                                             java.util.Map<String, String> __ctx, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_pushMessage(String message, 
                                             java.util.Map<String, String> __ctx, 
                                             IceInternal.Functional_VoidCallback __responseCb, 
                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                             IceInternal.Functional_BoolCallback __sentCb);

    public void end_pushMessage(Ice.AsyncResult __result);
}
