// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package chat;

public interface ChatListener extends Ice.Object,
                                      _ChatListenerOperations, _ChatListenerOperationsNC
{
    public static final String ice_staticId = "::chat::ChatListener";

    public static final long serialVersionUID = -8780329194809860477L;
}
