// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package utils;

public interface ChatManager extends Ice.Object,
                                     _ChatManagerOperations, _ChatManagerOperationsNC
{
    public static final String ice_staticId = "::utils::ChatManager";

    public static final long serialVersionUID = 5027430303590715751L;
}
