// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package utils;

public final class ChatManagerPrxHolder
{
    public
    ChatManagerPrxHolder()
    {
    }

    public
    ChatManagerPrxHolder(ChatManagerPrx value)
    {
        this.value = value;
    }

    public ChatManagerPrx value;
}
