// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package utils;

public final class ClientPrxHelper extends Ice.ObjectPrxHelperBase implements ClientPrx
{
    private static final String __read_name = "read";

    public void read(String message)
    {
        read(message, null, false);
    }

    public void read(String message, java.util.Map<String, String> __ctx)
    {
        read(message, __ctx, true);
    }

    private void read(String message, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_read(begin_read(message, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_read(String message)
    {
        return begin_read(message, null, false, false, null);
    }

    public Ice.AsyncResult begin_read(String message, java.util.Map<String, String> __ctx)
    {
        return begin_read(message, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_read(String message, Ice.Callback __cb)
    {
        return begin_read(message, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_read(String message, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_read(message, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_read(String message, Callback_Client_read __cb)
    {
        return begin_read(message, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_read(String message, java.util.Map<String, String> __ctx, Callback_Client_read __cb)
    {
        return begin_read(message, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_read(String message, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_read(message, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_read(String message, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_read(message, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_read(String message, 
                                      java.util.Map<String, String> __ctx, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_read(message, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_read(String message, 
                                      java.util.Map<String, String> __ctx, 
                                      IceInternal.Functional_VoidCallback __responseCb, 
                                      IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                      IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_read(message, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_read(String message, 
                                       java.util.Map<String, String> __ctx, 
                                       boolean __explicitCtx, 
                                       boolean __synchronous, 
                                       IceInternal.Functional_VoidCallback __responseCb, 
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                       IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_read(message, 
                          __ctx, 
                          __explicitCtx, 
                          __synchronous, 
                          new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_read(String message, 
                                       java.util.Map<String, String> __ctx, 
                                       boolean __explicitCtx, 
                                       boolean __synchronous, 
                                       IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__read_name, __cb);
        try
        {
            __result.prepare(__read_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(message);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_read(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __read_name);
    }

    public static ClientPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), ClientPrx.class, ClientPrxHelper.class);
    }

    public static ClientPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), ClientPrx.class, ClientPrxHelper.class);
    }

    public static ClientPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), ClientPrx.class, ClientPrxHelper.class);
    }

    public static ClientPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), ClientPrx.class, ClientPrxHelper.class);
    }

    public static ClientPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, ClientPrx.class, ClientPrxHelper.class);
    }

    public static ClientPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, ClientPrx.class, ClientPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::utils::Client"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, ClientPrx v)
    {
        __os.writeProxy(v);
    }

    public static ClientPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            ClientPrxHelper result = new ClientPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
